- hosts: all
  tasks:
  - name: download signing key
    apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present
    sudo: true
  - name: software properties
    apt: name=software-properties-common state=present
    sudo: true
  - name: oracle repo
    apt_repository: repo='ppa:webupd8team/java' state=present
    sudo: true
  - name: Deal with the Oracle license
    shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  - name: update
    apt: update_cache=yes cache_valid_time=3600
    sudo: true
  - name: java
    apt: name=oracle-java8-installer state=present  update-cache=yes force=yes
    sudo: true

  - name: copy app
    copy: src=app.jar dest=/monitor/app.jar
  - name: copy start script
    copy: src=start.sh dest=/monitor/start.sh
